-- Initial schema for Document Intelligence Agent
-- Generated by hand to match prisma/schema.prisma (could not run `prisma migrate dev`
-- in the sandbox because there is no network access / live Postgres instance).
-- Run `npx prisma migrate dev` locally against a real database instead of applying
-- this file directly if you'd rather have Prisma generate migrations itself; this
-- file is provided so `prisma migrate deploy` also works unmodified.

CREATE TYPE "InvoiceStatus" AS ENUM ('uploaded', 'processing', 'extracted', 'needs_review', 'reviewed', 'failed');
CREATE TYPE "DocumentType" AS ENUM ('pdf_text', 'scanned_image', 'excel', 'unknown');

CREATE TABLE "Invoice" (
    "id" TEXT NOT NULL,
    "vendorName" TEXT,
    "invoiceNumber" TEXT,
    "invoiceDate" TIMESTAMP(3),
    "grandTotal" DECIMAL(14,2),
    "status" "InvoiceStatus" NOT NULL DEFAULT 'uploaded',
    "confidence" DOUBLE PRECISION,
    "documentType" "DocumentType" NOT NULL DEFAULT 'unknown',
    "ocrUsed" BOOLEAN NOT NULL DEFAULT false,
    "extractionAttempts" INTEGER NOT NULL DEFAULT 0,
    "extractionError" TEXT,
    "uncertainFields" JSONB NOT NULL DEFAULT '[]',
    "rawExtractionJson" JSONB,
    "sourceFileName" TEXT NOT NULL,
    "sourceFilePath" TEXT NOT NULL,
    "mimeType" TEXT NOT NULL,
    "reviewedAt" TIMESTAMP(3),
    "reviewedBy" TEXT,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,
    CONSTRAINT "Invoice_pkey" PRIMARY KEY ("id")
);

CREATE TABLE "InvoiceLineItem" (
    "id" TEXT NOT NULL,
    "invoiceId" TEXT NOT NULL,
    "description" TEXT NOT NULL,
    "quantity" DECIMAL(14,3) NOT NULL,
    "unitPrice" DECIMAL(14,2) NOT NULL,
    "total" DECIMAL(14,2) NOT NULL,
    "uncertain" BOOLEAN NOT NULL DEFAULT false,
    "sortOrder" INTEGER NOT NULL DEFAULT 0,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,
    CONSTRAINT "InvoiceLineItem_pkey" PRIMARY KEY ("id")
);

CREATE INDEX "Invoice_status_idx" ON "Invoice"("status");
CREATE INDEX "Invoice_createdAt_idx" ON "Invoice"("createdAt");
CREATE INDEX "InvoiceLineItem_invoiceId_idx" ON "InvoiceLineItem"("invoiceId");

ALTER TABLE "InvoiceLineItem" ADD CONSTRAINT "InvoiceLineItem_invoiceId_fkey"
  FOREIGN KEY ("invoiceId") REFERENCES "Invoice"("id") ON DELETE CASCADE ON UPDATE CASCADE;
